lib/ssauction_live_web/router.ex
defmodule SSAuctionWeb.Router do
  use SSAuctionWeb, :router

  import SSAuctionWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SSAuctionWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SSAuctionWeb do
    pipe_through :browser

    live "/", AuctionLive.Index, :index
    live "/auctions", AuctionLive.Index, :index
    live "/auction/:id", AuctionLive.Show, :show
    live "/auction/:id/autonominationqueue", AuctionLive.AutoNominationQueue
    live "/auction/:id/bids", AuctionLive.Bids
    live "/auction/:id/rosteredplayers", AuctionLive.RosteredPlayers

    live "/team/:id", TeamLive.Show, :show
    live "/team/:id/bids", TeamLive.Bids
    live "/team/:id/rosteredplayers", TeamLive.RosteredPlayers

    live "/player/:id", PlayerLive.Show, :show

    # live "/all_players", AllPlayerLive.Index, :index
    # live "/all_players/new", AllPlayerLive.Index, :new
    # live "/all_players/:id/edit", AllPlayerLive.Index, :edit
    # live "/all_players/:id", AllPlayerLive.Show, :show
    # live "/all_players/:id/show/edit", AllPlayerLive.Show, :edit
    # live "/players", PlayerLive.Index, :index
    # live "/players/new", PlayerLive.Index, :new
    # live "/players/:id/edit", PlayerLive.Index, :edit
    # live "/players/:id", PlayerLive.Show, :show
    # live "/players/:id/show/edit", PlayerLive.Show, :edit
    # live "/rostered_players", RosteredPlayerLive.Index, :index
    # live "/rostered_players/new", RosteredPlayerLive.Index, :new
    # live "/rostered_players/:id/edit", RosteredPlayerLive.Index, :edit
    # live "/rostered_players/:id", RosteredPlayerLive.Show, :show
    # live "/rostered_players/:id/show/edit", RosteredPlayerLive.Show, :edit
    # live "/ordered_players", OrderedPlayerLive.Index, :index
    # live "/ordered_players/new", OrderedPlayerLive.Index, :new
    # live "/ordered_players/:id/edit", OrderedPlayerLive.Index, :edit
    # live "/ordered_players/:id", OrderedPlayerLive.Show, :show
    # live "/ordered_players/:id/show/edit", OrderedPlayerLive.Show, :edit
    # live "/bid_logs", BidLogLive.Index, :index
    # live "/bid_logs/new", BidLogLive.Index, :new
    # live "/bid_logs/:id/edit", BidLogLive.Index, :edit
    # live "/bid_logs/:id", BidLogLive.Show, :show
    # live "/bid_logs/:id/show/edit", BidLogLive.Show, :edit
    # live "/bids", BidLive.Index, :index
    # live "/bids/new", BidLive.Index, :new
    # live "/bids/:id/edit", BidLive.Index, :edit
    # live "/bids/:id", BidLive.Show, :show
    # live "/bids/:id/show/edit", BidLive.Show, :edit
  end

  # Other scopes may use custom stacks.
  # scope "/api", SSAuctionWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: SSAuctionWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", SSAuctionWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    # get "/users/register", UserRegistrationController, :new
    # post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", SSAuctionWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", SSAuctionWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/ssauction_live_web/views/layout_view.ex
defmodule SSAuctionWeb.LayoutView do
  use SSAuctionWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/ssauction_live_web/templates/layout/_user_menu.html.heex
<%= if @current_user do %>
  <span class="text-black"><%= @current_user.username %> |</span>
  <span class="underline text-blue-600 hover:text-blue-800"><%= link "Settings", to: Routes.user_settings_path(@conn, :edit) %></span>
  <span class="text-black">|</span>
  <span class="underline text-blue-600 hover:text-blue-800"><%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete %></span>
<% else %>
  <span class="underline text-blue-600 hover:text-blue-800"><%= link "Log in", to: Routes.user_session_path(@conn, :new) %></span>
<% end %>

lib/ssauction_live_web/templates/layout/app.html.heex
<header>
  <section class="container w-full m-5 p-3 bg-blue-200 text-blue-600 text-5xl font-bold">
    <div class="text-2xl">
      <a href="/">
        <img class="float-left mt-1"
          src={Routes.static_path(@conn, "/images/ship-steering-wheel-32.png")} alt="SSAuction"/>
        <span class="flex text-4xl hover:text-blue-800">
          <span class="font-extrabold nomargin">SS</span>
          <span class="font-medium nomargin">Auction</span>
        </span>
      </a>
    </div>
  </section>
</header>
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/ssauction_live_web/templates/layout/live.html.heex
<header>
  <section class="container w-full m-5 p-3 bg-blue-200 text-blue-600 text-5xl font-bold">
    <div class="flex text-2xl">
      <a href="/">
        <img class="float-left mt-1"
          src={Routes.static_path(@socket, "/images/ship-steering-wheel-32.png")} alt="SSAuction"/>
        <span class="text-4xl hover:text-blue-800">
          <span class="font-extrabold nomargin">SS</span>
          <span class="font-medium nomargin -ml-2">Auction</span>
        </span>
      </a>
      <%= if assigns[:links] do %>
        <span class="text-2xl font-medium mt-1">
          <%= for link_map <- @links do %>
            <span class="ml-2 text-slate-800">
              >
            </span>
            <span class="hover:text-blue-800">
              <%= link link_map.label, to: link_map.to %>
            </span>
          <% end %>
        </span>
      <% end %>
    </div>
  </section>
</header>
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/ssauction_live_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "SSAuction" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <%= @inner_content %>
  </body>
  <footer>
    <section class="container w-full h-20 m-5 p-3 bg-blue-200 text-blue-600 text-5xl font-bold">
      <div class="text-2xl">
        <span class="float-right flex mt-3 font-normal">
          <nav role="navigation">
            <%= render "_user_menu.html", assigns %>
          </nav>
        </span>
      </div>
    </section>
  </footer>
</html>